language: swift
osx_image: xcode11.2.1

branches:
  only:
    - master
    - develop

before_install:
  - brew update

script:
  - xcodebuild clean build -project r2-shared-swift.xcodeproj -scheme r2-shared-swift -quiet
